"""init migration

Revision ID: 0c54477d8dec
Revises: 
Create Date: 2025-06-17 12:00:36.634424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c54477d8dec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('event_is_open', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('Speaker',
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('speaker_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('speaker_topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('speaker_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_user_email'), 'User', ['user_email'], unique=True)
    op.create_table('Registration',
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('user_attended', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_index(op.f('ix_Registration_event_id'), 'Registration', ['event_id'], unique=False)
    op.create_index(op.f('ix_Registration_user_id'), 'Registration', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Registration_user_id'), table_name='Registration')
    op.drop_index(op.f('ix_Registration_event_id'), table_name='Registration')
    op.drop_table('Registration')
    op.drop_index(op.f('ix_User_user_email'), table_name='User')
    op.drop_table('User')
    op.drop_table('Speaker')
    op.drop_table('Event')
    # ### end Alembic commands ###
